# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript sources
RUN npm run build

# Expose ports if needed (optional)
# EXPOSE 8080

# Start the MCP server
CMD ["node", "build/index.js"]
